### ISSUE TITLE
Could not parse rotation with a decimal

### ISSUE THREAD

**Issue by GarthDB** [jonathantneal/postcss-logical#28] opened 2020-08-12 23:18 UTC
Using `transform: rotate(72.3deg);` results in the following error:

`postcss-transform-logical: could not parse rotate(72.3deg)`

**Comment by romainmenke** [comment] 2021-08-19 21:11
I think this is resolved (but probably not yet released).
I can't reproduce it on the main branch.

**Comment by romainmenke** [comment] 2021-12-22 15:59
Confirmed that this is fixed in the latest release.
Thank you for reporting this.

**Closed as completed by romainmenke** 2021-12-22 15:59 UTC
